export const data = JSON.parse("{\"key\":\"v-69ca7ca6\",\"path\":\"/programming/vue/2023%E5%B9%B4%E5%89%8D%E7%AB%AF%E9%9D%A2%E8%AF%95%E7%B3%BB%E5%88%97-JS%E7%AF%87.html\",\"title\":\"JavaScript 常见面试题总结\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"edit\",\"date\":\"2023-03-17T00:00:00.000Z\",\"category\":[\"前端面试\"],\"tag\":[\"JavaScript面试题\"],\"sticky\":true,\"lastUpdated\":true,\"footer\":\"JavaScript 常见面试题总结\",\"description\":\"JavaScript 常见面试题总结 参考自掘金《2023 前端面试系列-- JS 篇》 JS 的数据类型有哪些？ 基本数据类型（值类型）：Number、String、Boolean、Null、Undefined、Symbol、BigInt。保存在栈内存中。 复杂数据类型（引用类型）：Object、Function、Array、RegExp、Date 基本包装类型及单体内置对象（Global、Math）等。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.baidu.com/programming/vue/2023%E5%B9%B4%E5%89%8D%E7%AB%AF%E9%9D%A2%E8%AF%95%E7%B3%BB%E5%88%97-JS%E7%AF%87.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Kevin的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"JavaScript 常见面试题总结\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"JavaScript 常见面试题总结 参考自掘金《2023 前端面试系列-- JS 篇》 JS 的数据类型有哪些？ 基本数据类型（值类型）：Number、String、Boolean、Null、Undefined、Symbol、BigInt。保存在栈内存中。 复杂数据类型（引用类型）：Object、Function、Array、RegExp、Date 基本包装类型及单体内置对象（Global、Math）等。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"JavaScript面试题\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-03-17T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"JavaScript 常见面试题总结\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-03-17T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"JS 的数据类型有哪些？\",\"slug\":\"js-的数据类型有哪些\",\"link\":\"#js-的数据类型有哪些\",\"children\":[]},{\"level\":2,\"title\":\"null 和 undefined 的区别？\",\"slug\":\"null-和-undefined-的区别\",\"link\":\"#null-和-undefined-的区别\",\"children\":[]},{\"level\":2,\"title\":\"== 和 === 的区别？\",\"slug\":\"和-的区别\",\"link\":\"#和-的区别\",\"children\":[]},{\"level\":2,\"title\":\"如何遍历对象的属性？\",\"slug\":\"如何遍历对象的属性\",\"link\":\"#如何遍历对象的属性\",\"children\":[]}],\"readingTime\":{\"minutes\":2.59,\"words\":776},\"filePathRelative\":\"programming/vue/2023年前端面试系列-JS篇.md\",\"localizedDate\":\"2023年3月17日\",\"excerpt\":\"<h1> JavaScript 常见面试题总结</h1>\\n<p><a href=\\\"https://juejin.cn/post/7176644710847479869\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">参考自掘金《2023 前端面试系列-- JS 篇》</a></p>\\n<h2> JS 的数据类型有哪些？</h2>\\n<ul>\\n<li>基本数据类型（值类型）：Number、String、Boolean、Null、Undefined、Symbol、BigInt。保存在栈内存中。</li>\\n<li>复杂数据类型（引用类型）：Object、Function、Array、RegExp、Date 基本包装类型及单体内置对象（Global、Math）等。</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
